import type { ProductItem } from "@/types/product";

export const MOCK_PRODUCTS: ProductItem[] = [
  {
    _id: "mk-1",
    title: "Banarasi Rose Silk Saree",
    description: "Traditional woven silk saree with delicate zari borders.",
    price: 149,
    category: "saree",
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80"],
    stock: 12,
  },
  {
    _id: "mk-2",
    title: "Printed Cotton Saree",
    description: "Breathable cotton saree with soft floral motifs for daily wear.",
    price: 59,
    category: "saree",
    images: ["https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=800&q=80"],
    stock: 22,
  },
  {
    _id: "mk-3",
    title: "Embroidered Salwar Set",
    description: "Comfort-fit salwar suit with lightweight dupatta and neat embroidery.",
    price: 79,
    category: "clothing",
    images: ["https://images.unsplash.com/photo-1621184455862-c163dfb30e0f?auto=format&fit=crop&w=800&q=80"],
    stock: 16,
  },
  {
    _id: "mk-4",
    title: "Evening Midi Dress",
    description: "Elegant solid-tone midi dress for festive evenings and parties.",
    price: 95,
    category: "clothing",
    images: ["https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80"],
    stock: 10,
  },
  {
    _id: "mk-5",
    title: "Structured Leather Tote",
    description: "Daily work tote with zip closure, reinforced straps and inner pockets.",
    price: 110,
    category: "bags",
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80"],
    stock: 14,
  },
  {
    _id: "mk-6",
    title: "Classic Sling Bag",
    description: "Compact crossbody sling bag with adjustable strap and magnetic flap.",
    price: 69,
    category: "bags",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80"],
    stock: 20,
  },
  {
    _id: "mk-7",
    title: "Hydra Matte Lip Color",
    description: "Long-lasting matte lipstick enriched with hydrating oils.",
    price: 24,
    category: "cosmetics",
    images: ["https://images.unsplash.com/photo-1599733589046-10c005739f5e?auto=format&fit=crop&w=800&q=80"],
    stock: 50,
  },
  {
    _id: "mk-8",
    title: "Glow Foundation SPF 25",
    description: "Buildable medium coverage foundation with natural satin finish.",
    price: 31,
    category: "cosmetics",
    images: ["https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?auto=format&fit=crop&w=800&q=80"],
    stock: 28,
  },
  {
    _id: "mk-9",
    title: "Vitamin C Brightening Serum",
    description: "Lightweight serum that supports brighter skin and even tone.",
    price: 35,
    category: "skincare",
    images: ["https://images.unsplash.com/photo-1629198735660-e39ea93f5c18?auto=format&fit=crop&w=800&q=80"],
    stock: 30,
  },
  {
    _id: "mk-10",
    title: "Hydrating Gel Moisturizer",
    description: "Oil-free gel moisturizer for all-day hydration without heaviness.",
    price: 28,
    category: "skincare",
    images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80"],
    stock: 34,
  },
];
